blog/models/__init__.py
from blog.models.articles import Articles
from blog.models.user import Users

__all__ = [
    "Users",
    "Articles",
]

blog/models/articles.py
from flask_login import UserMixin
from sqlalchemy import Column, Integer, String, Boolean

from blog.models.database import db


class Articles(db.Model, UserMixin):
    id = Column(Integer, primary_key=True)
    title = Column(String(150))
    text = Column(String)
    # author = relationship('Users.id')

blog/models/database.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

__all__ = [
    'db',
]

blog/models/user.py
from flask_login import UserMixin
from sqlalchemy import Column, Integer, String, Boolean
from blog.models.database import db


class Users(db.Model, UserMixin):
    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False)
    email = Column(String(255), unique=True)
    password = Column(String(255))
    is_staff = Column(Boolean, nullable=False, default=False)

    def __init__(self, username, email, password, is_staff):
        self.username = username
        self.email = email
        self.password = password
        self.is_staff = is_staff

blog/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, PasswordField, SubmitField


class UserRegisterForm(FlaskForm):
    username = StringField('Username', )
    email = StringField('E-mail', [validators.DataRequired(), validators.Email()])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm_password', message='Invalid password')
    ])
    confirm_password = PasswordField('Confirm Password', [validators.DataRequired()])
    submit = SubmitField('Register')

blog/app.py
from flask import Flask

from blog.articles.views import articles
from blog.auth.views import auth
from blog.user.views import user
from blog.visit.views import visits
from blog import commands
from blog.extensions import db, login_manager, migrate, csrf
from blog.models.user import Users


def create_app() -> Flask:
    app = Flask(__name__)
    app.config.from_object('blog.config')

    register_extensions(app)
    register_blueprints(app)
    register_commands(app)
    return app


def register_blueprints(app: Flask):
    app.register_blueprint(articles)
    app.register_blueprint(auth)
    app.register_blueprint(user)
    app.register_blueprint(visits)


def register_commands(app: Flask):
    app.cli.add_command(commands.create_init_user)


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db, compare_type=True)
    csrf.init_app(app)

    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return Users.query.get(int(user_id))

blog/articles/views.py
from flask import Blueprint, render_template, redirect, url_for
from werkzeug.exceptions import NotFound

articles = Blueprint('articles', __name__, url_prefix='/articles', static_folder='../static')


ARTICLES = {
    1: {
        'title': 'Символы Юникода',
        'text': 'Добавлять юникод-символы в строковые литералы можно не только с помощью их номеров, но и по их названиям.',
        'author': 1
    },
    2: {
        'title': 'Функция zip',
        'text': 'Функция zip создаёт итератор, который комбинирует элементы нескольких списков. Это позволяет осуществлять параллельный обход списков в циклах for или, например, выполнять параллельную сортировку.',
        'author': 2
        },
    3: {
        'title': 'Проверка отношения классов',
        'text': 'Для того, чтобы проверить отношения двух классов или экземпляров (является ли класс классом наследником), есть две простые встроенные функции isinstance(object, classinfo) и issubclass(class, classinfo). instance - возвращает True, если объект является экземпляром класса либо экземпляром подкласса данного класса. issubclass — проверяет является ли класс наследником другого класса. Данные функции зачастую применяются в ООП.',
        'author': 3
        },
}


@articles.route('/')
def articles_list():
    return render_template(
        'articles/list.html',
        articles=ARTICLES,
    )


@articles.route('/<int:pk>')
def get_articles(pk: int):
    try:
        articles_id = ARTICLES[pk]
        articles_title = ARTICLES[pk]['title']
        articles_text = ARTICLES[pk]['text']
        articles_author = ARTICLES[pk]['author']
    except KeyError:
        raise NotFound(f'Articles id {pk} not found')
    return render_template(
        'articles/details.html',
        articles_id=articles_id,
        articles_title=articles_title,
        articles_text=articles_text,
        articles_author=articles_author
    )

blog/user/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user, login_user
from sqlalchemy.exc import IntegrityError
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash

from blog.extensions import db
from blog.forms.user import UserRegisterForm
from blog.models.user import Users

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@user.route('register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile', pk=current_user.id))

    form = UserRegisterForm(request.form)
    errors = []
    if request.method == 'POST' and form.validate_on_submit():
        if Users.query.filter_by(email=form.email.data).count():
            form.email.errors.append('email not unique')
            return render_template('users/register.html', form=form)

        _user = Users(
            email=form.email.data,
            username=form.username.data,
            password=generate_password_hash(form.password.data)
        )

        db.session.add(_user)
        db.session.commit()
        login_user(_user)

        return render_template(
            'users/register.html',
            form=form,
            errors=errors
        )


@user.route('/')
def user_list():
    users = Users.query.all()
    return render_template(
        'users/list.html',
        users=users,
    )


@user.route('/<int:pk>')
@login_required
def profile(pk: int):
    users = Users.query.filter_by(id=pk).one_or_none()
    if not users:
        raise NotFound(f"User {pk} doesn't exist!")

    return render_template(
        'users/profile.html',
        users=users,
    )

blog/visit/views.py
from flask import Blueprint, session, render_template


visits = Blueprint('visits', __name__, url_prefix='/', static_folder='../static')


@visits.route('/')
def index():
    if 'visits' in session:
        session['visits'] = session.get('visits') + 1
    else:
        session['visits'] = 1
    return render_template('visit/list.html', visits=session.get("visits"))


@visits.route('/del_visit', methods=['DELETE'])
def del_visit():
    session.pop('visits', None)
    return render_template('visit/list.html')

blog/templates/articles/details.html
{% extends 'base.html' %}

{% block title %} Articles {% endblock %}

{% block body %}
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">{{ articles_title }}</h4>
        <p>{{ articles_text }}</p>
        <hr>
        <a class="mb-0" href="{{ url_for('user.get_user', pk=articles_author) }}">{{ articles_author }}</a>
    </div>
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} Articles list {% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Articles: </h1>
            {% for article in articles %}
                <ul>
                    <li><a href="{{ url_for('articles.get_articles', pk=article) }}">{{ articles[article]['title'] }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>

{% endblock %}

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
    <title>
        {% block title %} Base {% endblock %}
    </title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container-fluid">
    {% block body %}{% endblock %}
</div>

{% block js %}
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}
</body>
</html>

blog/templates/macro/formhelpers.html
{% macro render_field(field) %}
    <div class="mb-3 row">
        {{ field.lable(class="col-sm-2 col-form-label") }}
        <div class="col-sm-3">
            {{ field(class="form" + (" is_invalid" if field.errors else ""))| safe }}
            {% if field.errors %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

        </div>
    </div>
{% endmacro %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('visits.index') }}">Main page</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.user_list') }}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('articles.articles_list') }}">Аrticles</a>
                </li>
                {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                {% else %}
                    <a href="{{ url_for('auth.login') }}"
                       class="nav-link {% if request.endpoint == 'auth.login' -%}active{%- endif %}">
                        Login
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %}
    Users list
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Users:</h1>
            {% for user in users %}
                <ul>
                    <li><a href="{{ url_for('user.profile', pk=user.id) }}">{{ user.email }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
    User profile
{% endblock %}

{% block body %}
    <h1>{{ user.username }}</h1>
{% endblock %}

blog/templates/users/register.html
{% extends 'base.html' %}
{% from "macro/formhelpers.html" import render_field %}

{% block title %}
    User register
{% endblock %}

{% block body %}
    {% if errors %}
        {% for error in errors %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endfor %}
    {% endif %}
    <form method="post">
        {{ form.csrf_token }}
        {% for field in ['username', 'email', 'password', 'confirm_password'] %}
            {{ render_field(form[field]) }}
        {% endfor %}
        {{ form.submit(class="btn btn-primary mb-3") }}
    </form>
{% endblock %}

blog/templates/visit/list.html
{% extends 'base.html' %}

{% block title %} Visit {% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h4>Количество посещений на сайте {{ visits }}</h4>
        </div>
    </div>
{% endblock %}